trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
resources:
  containers:
  - container: buildj
    image: tokera/buildj1:latest
pool:
  vmImage: 'Ubuntu-16.04'
container: buildj
steps:
- script: ./compile.sh
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'ate-jar'
    pathtoPublish: 'target/ate-0.1.jar'
  displayName: 'Publishing ATE jar'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'ate-libs'
    pathtoPublish: 'target/libs.zip'
  displayName: 'Publishing ATE libs'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'ate-repo'
    pathtoPublish: 'repo.zip'
  displayName: 'Publishing ATE maven repo'
