trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
resources:
  containers:
  - container: buildj
    image: tokera/buildj:latest
pool:
  vmImage: 'Ubuntu-16.04'
container: buildj
steps:
- script: sudo ./compile.sh
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'ate-jar'
    pathtoPublish: 'target/*.jar'
  displayName: 'Publishing ATE jar'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'ate-repo'
    pathtoPublish: 'repo.zip'
  displayName: 'Publishing ATE maven repo'
