[alias]
b = "build"
c = "check"
t = "test"
r = "run"

[package]
name = "ate"
version = "0.1.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "Distributed immutable data store with strong encryption and authentication"
license-file = "LICENSE"
keywords = ["immutable", "database", "kafka", "blockchain", "datastore", "immutable objects", "quantum algorithms", "materialized views", "materialized view", "immutable store", "nosql"]
categories = ["Asynchronous", "Caching", "Cryptography", "Database implementations"]
repository = "https://github.com/john-sharratt/ate-2.0"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
uuid = { version = "*", features = ["serde", "v4"] }
tokio = { version = "*", features = ["full", "signal", "process"] }
serde = { version = "*", features = ["derive"] }
serde-big-array = "*"
serde_json = "*"
rmp = "*"
rmp-serde = "*"
derive-new = "*"
bytes = "*"
futures = "*"
futures-util = "*"
hash = "*"
fxhash = "*"
async-trait = "*"
fastrand = "*"
rust-crypto = "*"
rand = "*"
rand_chacha = "*"
buffered_offset_reader = "*"
async-drop = "*"
typed-arena = "*"
snap = "*"
openssl = { version = "*", features = ["vendored"] }
once_cell = "*"
pqcrypto-falcon = "*"
pqcrypto-traits = "*"
sha3 = "*"
multimap = "*"
hex = "*"
chrono = "*"
pnet = "*"
log = "0.4.11"

[dev-dependencies]
ctor = "*"