[workspace]
members = [
    "lib",
    "ateweb",
    "atefs",
    "atedb",
    "auth",
    "files",
    "wasm-bus",
    "tokterm",
]

[profile.dev]
opt-level = 0
debug = 2
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = 1
debug-assertions = false
overflow-checks = false
lto = 'fat'
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false