[alias]
b = "build"
c = "check"
t = "test"
r = "run"

[package]
name = "ate"
version = "2.0.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
uuid = { version = "*", features = ["serde", "v4"] }
tokio = { version = "*", features = ["full"] }
serde = { version = "*", features = ["derive"] }
serde-big-array = "*"
serde_json = "*"
rmp = "*"
rmp-serde = "*"
derive-new = "*"
bytes = "*"
futures = "*"
futures-util = "*"
hash = "*"
fxhash = "*"
async-trait = "*"
fastrand = "*"
rust-crypto = "*"
rand = "*"
rand_chacha = "*"
buffered_offset_reader = "*"
async-drop = "*"
typed-arena = "*"
snap = "*"
openssl = { version = "*", features = ["vendored"] }
once_cell = "*"
pqcrypto-falcon = "*"
pqcrypto-traits = "*"
sha3 = "*"
multimap = "*"
hex = "*"

[dev-dependencies]
ctor = "*"