[workspace]
members = [
    "lib",
    "ateweb",
    "atefs",
    "atedb",
    "auth",
    "files",
    "wasm-bus",
    "term-lib",
    "tokterm",
    "tokweb",
    "grammar"
]

[profile.release]
debug = 1
