[package]
name = "ate"
version = "0.1.7"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "Distributed immutable data store with strong encryption and authentication"
license-file = "LICENSE"
keywords = ["immutable", "database", "blockchain", "nosql", "materialized"]
categories = ["asynchronous", "caching", "cryptography", "database-implementations"]
repository = "https://github.com/john-sharratt/ate"
readme = "README.md"

[dependencies]
uuid = { version = "0.8.2", features = ["serde", "v4"] }
tokio = { version = "1.3.0", features = ["full", "signal", "process"] }
serde = { version = "1.0.124", features = ["derive"] }
serde-big-array = "0.3.2"
serde_json = "1.0.64"
rmp = "0.8.10"
rmp-serde = "0.15.4"
derive-new = "0.5.9"
bytes = "1.0.1"
futures = "0.3.13"
futures-util = "0.3.11"
hash = "0.3.0"
fxhash = "0.2.1"
async-trait = "0.1.48"
fastrand = "1.4.0"
rust-crypto = "0.2.36"
rand = "0.8.3"
rand_chacha = "0.3.0"
buffered_offset_reader = "0.6.0"
snap = "1.0.4"
openssl = { version = "0.10.33", features = ["vendored"] }
once_cell = "1.7.2"
pqcrypto-falcon = "0.2.5"
pqcrypto-traits = "0.3.3"
sha3 = "0.9.1"
multimap = "0.8.2"
hex = "0.4.3"
chrono = "0.4.19"
pnet = "0.27.2"
log = "0.4.14"
cached = "0.23.0"
parking_lot = "0.11.1"
hashlink = "0.6.0"

[dev-dependencies]
ctor = "0.1.19"
rust_decimal = "1.10.3"
names = "0.11.0"
env_logger = "0.8.3"