[workspace]
members = [
    "lib",
    "ateweb",
    "atefs",
    "atedb",
    "atessh",
    "atesess",
    "atenet",
    "auth",
    "comms",
    "crypto",
    "files",
    "wasm-bus/lib",
    "wasm-bus/types",
    "wasm-bus/macros",
    "wasm-bus/fuse",
    "wasm-bus/reqwest",
    "wasm-bus/ws",
    "wasm-bus/process",
    "wasm-bus/time",
    "wasm-bus/tty",
    "wasm-bus/tok",
    "wasm-bus/hello",
    "wasm-bus/webgl",
    "wasm-bus/mio",
    "term-lib",
    "tokera",
    "tokterm",
    "tokweb",
    "grammar",
    "examples/crypto-bus",
    "examples/tcp-listener",
    "examples/tcp-client",
    "examples/multi-threading",
    "examples/thread-local",
    "examples/wasm64-example",
    "examples/ws-client"
]
