[package]
name = "ate-auth"
version = "1.1.0"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "Represents a standardized data model and API for authenticating an ATE chain-of-trust"
license = "MIT OR Apache-2.0"
keywords = ["immutable", "authentication" ]
categories = ["data-structures"]
repository = "https://github.com/john-sharratt/ate/auth"
readme = "README.md"

[dependencies]
log = "0.4.*"
env_logger = "0.8.*"
parking_lot = "0.11.*"
futures = "0.3.*"
futures-util = "0.3.*"
async-trait = "0.1.*"
bytes = "1.0.*"
fxhash = "0.2.*"
fastrand = "1.4.*"
tokio = { version = "1.3.*", features = ["full", "signal", "process"] }
serde = { version = "1.0.*", features = ["derive"] }
ate = { version = "0.2.*", path = "../lib" }
chrono = { version = "0.4.*", features = ["serde"] }
isocountry = "0.3.*"
url = "2.2.*"
rpassword = "0.0.*"

[dev-dependencies]
regex = "*"
clap = "3.0.0-beta.2"
ctrlc = "*"
bincode = "*"
shellexpand = "*"