[package]
name = "ate-auth"
version = "1.4.2"
authors = ["Johnathan Sharratt <johnathan.sharratt@gmail.com>"]
edition = "2018"
description = "Represents a standardized data model and API for authenticating an ATE chain-of-trust"
license = "MIT OR Apache-2.0"
keywords = [ "authentication", "cli", "authorization", "crypto" ]
categories = [ "data-structures", "command-line-utilities", "authentication", "cryptography" ]
repository = "https://github.com/john-sharratt/ate/auth"
readme = "README.md"

[dependencies]
ate = { version = "0.6.*", path = "../lib" }
tokio = { version = "1.3.*", features = ["full", "signal", "process"] }
serde = { version = "1.0.*", features = ["derive"] }
log = { version = "0.4.*", features = [ "release_max_level_info" ] }
env_logger = "0.8.*"
parking_lot = "0.11.*"
futures = "0.3.*"
futures-util = "0.3.*"
async-trait = "0.1.*"
bytes = "1.0.*"
fxhash = "0.2.*"
fastrand = "1.4.*"
chrono = { version = "0.4.*", features = ["serde"] }
isocountry = "0.3.*"
url = "2.2.*"
rpassword = "0.0.*"
regex = "1.4.*"
hex = "0.4.*"
google-authenticator = "0.2.*"
qrcode = "0.12.*"
base64 = "0.13.*"
shellexpand = "2.1.0"
clap = "3.0.0-beta.2"
ctrlc = "3.1.*"
bincode = "1.3.*"