name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_MIN_STACK: 20971520

jobs:
  lib:
    name: Test ATE Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Run Tests
      run: |
        cd lib
        cargo test

  tokterm:
    name: Build Tokera/Wasmer Terminal
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build Terminal WASM
      run: |
        cd tokterm
        cargo build
    - name: Build NPM
      run: |
        npm i
        npm run build
