[package]
name = "tcp-client"
version = "0.0.1"
authors = ["John Sharratt <john.sharratt@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "An example TCP client."
repository = "https://github.com/tokera.com/ate"
readme = "README.md"
keywords = [
    "wasm",
    "tcp",
]
categories = ["network-programming"]
edition = "2021"

[dependencies]
#socket2 = { git = "https://github.com/john-sharratt/socket2.git" }
#libc = { git = "https://github.com/john-sharratt/libc.git" }
#tokio = { git = "https://github.com/john-sharratt/tokio.git" }
#ring = { git = "https://github.com/john-sharratt/ring.git", branch = "v0.16.20" }
